### ISSUE TITLE
Timing?

### ISSUE THREAD

**Issue by f3r** [ironhack/movies-interview-challenge#1]
Hi @nizaroni,

Interesting exercise! when do you think it's the best timing to share this with students?

cc/ @papuarza

**Comment by nizaroni** [comment]
Hey guys! I made this in a rush, but this challenge is supposed to be for interviewing potential instructors. Specifically, this is for instructors experienced in other tech stacks to see how well they can learn our technologies. It's based off of an existing student exercise (https://github.com/ironhack/lab-mongoose-movies).

Should I put this somewhere else? Does anybody else have a challenge like this one for potential instructors?

**Comment by f3r** [comment]
Hi @nizaroni!

Typically, the process for interviewing instructors goes something like this:

1. Coding challenge: [Escape the Mines](https://hackmd.io/s/SkWQGgUs)
1. Personal interview
1. Internal Class ([Sample invitation](http://materials.ironhack.com/BwBghgJgnMBmYFpgGYBsBWBAWVAjKCUuAjMAhMRugMag7WpA))
1. Offer
1. Hired

We manage the pipeline through Recruitee, do you have an account?

Also, I think this lab is good as well, perhaps we could rename it to `instructor-interview-challenge-movies`?
